"""
Tree Viewer Database Layer

Handles reading vault data from CSV and markdown files.
"""

import os
import re
from pathlib import Path
from typing import Dict, List, Any, Optional
import pandas as pd


def load_vault_csv(vault_path: str) -> pd.DataFrame:
    """
    Load the vault_notes.csv file generated by vault_crawler.py.

    Args:
        vault_path: Path to the vault root

    Returns:
        DataFrame with all note metadata
    """
    csv_path = Path(vault_path) / "vault_notes.csv"

    if not csv_path.exists():
        raise FileNotFoundError(
            f"vault_notes.csv not found at {csv_path}. "
            "Run ./crawl_vault.sh first."
        )

    df = pd.read_csv(csv_path)

    # Fill NaN values with empty strings for string columns
    for col in df.columns:
        if df[col].dtype == object:
            df[col] = df[col].fillna('')

    return df


def get_unique_values(df: pd.DataFrame, column: str) -> List[str]:
    """
    Get unique non-empty values for a column.

    Args:
        df: Notes DataFrame
        column: Column name

    Returns:
        Sorted list of unique values
    """
    if column not in df.columns:
        return []

    values = df[column].dropna().unique().tolist()
    # Filter out empty strings and sort
    values = sorted([v for v in values if v and str(v).strip()])
    return values


def get_filterable_columns(df: pd.DataFrame) -> List[str]:
    """
    Get columns that are suitable for filtering.

    Excludes 'name' and 'file_path' as they're identifiers, not filters.

    Args:
        df: Notes DataFrame

    Returns:
        List of column names suitable for filtering
    """
    exclude = {'name', 'file_path'}
    return [col for col in df.columns if col not in exclude]


if __name__ == "__main__":
    # Example usage for manual testing
    vault_path = "."

    print("Loading vault CSV...")
    df = load_vault_csv(vault_path)
    print(f"Loaded {len(df)} notes")
    print(f"\nColumns: {list(df.columns)}")

    print("\nFilterable columns:")
    for col in get_filterable_columns(df):
        values = get_unique_values(df, col)
        print(f"  {col}: {values}")

    print("\nSample data:")
    print(df.head())
